const data = {
    productItems:[
        {
            id:"1",
            name:"Carte d'Or Extra Barista",
            price:"89.90",
            image:"./pics/1.jpg",
            group:"yazaozel",
            altgroup:"dondurma",
        },
        {
            id:"2",
            name:"Eti Alaska Frigo Sütlü",
            price:"90.00",
            image:"./pics/2.jpg",
            group:"yazaozel",
            altgroup:"dondurma",
        },
        {
            id:"3",
            name:"Eti Alaska Frigo Bitter",
            price:"90.00",
            image:"./pics/3.jpg",
            group:"yazaozel",
            altgroup:"dondurma",
        },
        {
            id:"4",
            name:"Golf Bravo Karadut",
            price:"25.00",
            image:"./pics/4.jpeg",
            group:"yazaozel",
            altgroup:"dondurma",
        },
        {
            id:"5",
            name:"Golf Roko Dark",
            price:"12.00",
            image:"./pics/5.jpg",
            group:"yazaozel",
            altgroup:"dondurma",
        },
        {
            id:"6",
            name:"Golf Maraşım Fıstık Sade",
            price:"79.90",
            image:"./pics/6.jpeg",
            group:"yazaozel",
            altgroup:"dondurma",
        },
        {
            id:"7",
            name:"Kuzeyden",
            price:"59.50",
            image:"./pics/7.jpg",
            group:"yazaozel",
            altgroup:"suVeicecek",
        },
        {
            id:"8",
            name:"Coca Cola & Peyman Paketi",
            price:"45.70",
            image:"./pics/8.jpg",
            group:"yazaozel",
            altgroup:"suVeicecek",
        },
        {
            id:"9",
            name:"Coca-Cola İkilisi",
            price:"54.40",
            image:"./pics/9.jpg",
            group:"yazaozel",
            altgroup:"suVeicecek",
        },
        {
            id:"10",
            name:"Schweppes Mandalina",
            price:"37.50",
            image:"./pics/10.jpg",
            group:"yazaozel",
            altgroup:"suVeicecek",
        },
        {
            id:"11",
            name:"Lipton Üçlüsü",
            price:"85.53",
            image:"./pics/11.jpg",
            group:"yazaozel",
            altgroup:"suVeicecek",
        },
        {
            id:"12",
            name:"Ruffles & Pepsi Paketi",
            price:"45.89",
            image:"./pics/12.png",
            group:"yazaozel",
            altgroup:"suVeicecek",
        },
        {
            id:"13",
            name:"Pepsi & Çerezza İkilisi",
            price:"39.89",
            image:"./pics/13.jpg",
            group:"yazaozel",
            altgroup:"suVeicecek",
        },
        {
            id:"14",
            name:"Lay's & Ice Tea Paketi",
            price:"45.07",
            image:"./pics/14.png",
            group:"yazaozel",
            altgroup:"suVeicecek",
        },
        {
            id:"15",
            name:"Doritos Nacho & Pepsi Max",
            price:"52.40",
            image:"./pics/15.png",
            group:"yazaozel",
            altgroup:"suVeicecek",
        },
        {
            id:"16",
            name:"Lipton Ice Tea Şeftali",
            price:"17.52",
            image:"./pics/16.png",
            group:"yazaozel",
            altgroup:"suVeicecek",
        },
        
        
    ]
}
export default data;